// @license
// Copyright (c) Audanika. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/aud_dsp_synth_version_test.dart.
// coverage:ignore-file

/// The version of the `aud_dsp_synth` package.
const String audDspSynthVersion = '0.0.1';
